export const INLINE_TOOLBAR_BUTTONS = {
  BOLD: 'textInlineStyleButton_Bold',
  ITALIC: 'textInlineStyleButton_Italic',
  UNDERLINE: 'textInlineStyleButton_Underline',
  COLOR: 'TextColorButton',
  TITLE: 'textBlockStyleButton_Title',
  QUOTE: 'textBlockStyleButton_Quote',
  ORDERED_LIST: 'textBlockStyleButton_Numbering',
  UNORDERED_LIST: 'textBlockStyleButton_Bullets',
  ALIGNMENT: 'textDropDownButton_Alignment',
  TEXT_ALIGN_CENTER: 'textAlignmentButton_Center',
  TEXT_ALIGN_LEFT: 'textAlignmentButton_Left',
  TEXT_ALIGN_RIGHT: 'textAlignmentButton_Right',
  LINE_SPACING: 'LineSpacingButton',
  LINK: 'LinkButton',
  CODE_BLOCK: 'TextCodeBlockButton',
};
