import deepFreeze from 'deep-freeze';

/*eslint-disable*/
export const contentState = deepFreeze({
  blocks: [
    {
      key: '1l5jh',
      text: 'the first block plain text',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: '8dgob',
      text: '',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: '8k98f',
      text: ' ',
      type: 'atomic',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [
        {
          offset: 0,
          length: 1,
          key: 0,
        },
      ],
      data: {},
    },
    {
      key: '9qqjd',
      text: '',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: '7ppa3',
      text: 'plain text with\nsoft new line',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: '5umtr',
      text: 'plain text with inline styles',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [
        {
          offset: 0,
          length: 5,
          style: 'BOLD',
        },
        {
          offset: 6,
          length: 4,
          style: 'ITALIC',
        },
        {
          offset: 11,
          length: 4,
          style: 'UNDERLINE',
        },
        {
          offset: 16,
          length: 6,
          style: 'color4',
        },
      ],
      entityRanges: [],
      data: {},
    },
    {
      key: '763qd',
      text: '',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: 'b3pio',
      text: ' ',
      type: 'atomic',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [
        {
          offset: 0,
          length: 1,
          key: 1,
        },
      ],
      data: {},
    },
    {
      key: '4g4vq',
      text: '',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: '9jho5',
      text: 'plain text aligned to right',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {
        textAlignment: 'right',
      },
    },
    {
      key: '2lf2p',
      text: '',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: 'a7p3q',
      text: 'plain text with link',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [
        {
          offset: 16,
          length: 4,
          style: 'UNDERLINE',
        },
      ],
      entityRanges: [
        {
          offset: 16,
          length: 4,
          key: 2,
        },
      ],
      data: {},
    },
    {
      key: '6f866',
      text: 'טקסט בעברית',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: 'lg4h',
      text: 'по-русски',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: '4lhkf',
      text: '',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: 'f4961',
      text: ' ',
      type: 'atomic',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [
        {
          offset: 0,
          length: 1,
          key: 3,
        },
      ],
      data: {},
    },
    {
      key: '6cl6g',
      text: '',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: '8k5qh',
      text: 'ordered list item 1',
      type: 'ordered-list-item',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: 'dhjjv',
      text: 'ordered list item 2',
      type: 'ordered-list-item',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: 'eqfkh',
      text: 'ordered list item 3',
      type: 'ordered-list-item',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: '5utu3',
      text: '',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: 'etgqn',
      text: ' ',
      type: 'atomic',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [
        {
          offset: 0,
          length: 1,
          key: 4,
        },
      ],
      data: {},
    },
    {
      key: 'dmpgk',
      text: '',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: '5tksk',
      text: 'unordered list item 1',
      type: 'unordered-list-item',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: '8tui7',
      text: 'unordered list item 2',
      type: 'unordered-list-item',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: 'co42v',
      text: 'unordered list item 3',
      type: 'unordered-list-item',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: '206vl',
      text: '',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: 'capn1',
      text: ' ',
      type: 'atomic',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [
        {
          offset: 0,
          length: 1,
          key: 5,
        },
      ],
      data: {},
    },
    {
      key: '6q0d5',
      text: '',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: 'hccp',
      text:
        'Long text block: Rick and Morty is a fascinating show. Boiled down to its most fundamental roots, it’s simply a well-plotted, zany, sci-fi comedy. Still, its impact on viewers can’t be overstated, both for fans who see it as a philosophical reference point (and for those who use it as an excuse monstrous behavior). What about this seemingly innocent Adult Swim cartoon drives people so wild? Brilliant writing and content are a big part of it. Even the most innocuous moment can mean the world on Rick and Morty, giving the series a wildcard edge that sets it apart from the rest modern television. No one has partnered fart jokes with careful looks into the human soul like Dan Harmon and Justin Roiland and their toxic love letter to the human heart. Lost? Watch Rick and Morty. But if you’re curious about the best moments from the cartoon that launched a million catchphrases, you are in luck. Here are the best Rick and Morty quotes. For longtime fans, consider it a chance to revisit the best moments from the series (and a good reminder of just how much Rick garbles his lines). For new fans, it’s a taste of what you’ve been missing. As for folks who have tried but never found a connection with the show, we hear The Good Place is on Netflix and is worth your time. Let’s get started.',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: '6ol58',
      text: '',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: 'bra0f',
      text: ' ',
      type: 'atomic',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [
        {
          offset: 0,
          length: 1,
          key: 6,
        },
      ],
      data: {},
    },
    {
      key: 'c0h3d',
      text: '',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: '15vcf',
      text: '',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: 'd03nm',
      text: 'const codeBlock = this;',
      type: 'code-block',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: 'fv24h',
      text:
        'Listen, Jerry, I don’t want to overstep my bounds or  anything. It’s your house. It’s your world. You’re a real Julius Caesar,  but I’ll tell you some, tell you how-how I feel about school, Jerry.  It’s a waste of time, a bunch of people running around, bumping into  each other. G-guy up front says, “two plus two.” The people in the back  say, “four.” Then the bell rings, and they give you a carton of milk and  a piece of paper that says you can take a dump or something. I mean,  it’s—it’s not a place for smart people, Jerry, and I know that’s not a  popular opinion, but it’s my two cents on the issue.',
      type: 'blockquote',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: 'abcd123',
      text: 'heading1',
      type: 'header-one',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: 'jbdi',
      text: 'heading2',
      type: 'header-two',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: '43okj',
      text: 'heading3',
      type: 'header-three',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: '6i6e6',
      text: 'heading4',
      type: 'header-four',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: '4sgqv',
      text: 'heading5',
      type: 'header-five',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: 'f7sum',
      text: 'heading6',
      type: 'header-six',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: 'cppg8',
      text: 'block that contains a #hashtag',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: 'c1ucv',
      text: '@Test One mention',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [
        {
          offset: 0,
          length: 9,
          key: 7,
        },
      ],
      data: {},
    },
    {
      key: '3cvh3',
      text: 'block with line spacing 3',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {
        dynamicStyles: {
          'line-height': '3',
          'padding-top': '2px',
          'padding-bottom': '3px',
        },
      },
    },
    {
      key: '5r3j6',
      text: 'block with link.com',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [
        {
          offset: 11,
          length: 8,
          style: 'UNDERLINE',
        },
      ],
      entityRanges: [
        {
          offset: 11,
          length: 8,
          key: 8,
        },
      ],
      data: {
        dynamicStyles: {
          'line-height': '3',
          'padding-top': '2px',
          'padding-bottom': '3px',
        },
      },
    },
    {
      key: 'b1md3',
      text: 'block with more links',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [
        {
          offset: 11,
          length: 4,
          style: 'UNDERLINE',
        },
        {
          offset: 16,
          length: 5,
          style: 'UNDERLINE',
        },
      ],
      entityRanges: [
        {
          offset: 11,
          length: 4,
          key: 9,
        },
        {
          offset: 16,
          length: 5,
          key: 10,
        },
      ],
      data: {
        dynamicStyles: {
          'line-height': '3',
          'padding-top': '2px',
          'padding-bottom': '3px',
        },
      },
    },
    {
      key: 'bra1e',
      text: ' ',
      type: 'atomic',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [
        {
          offset: 0,
          length: 1,
          key: 11,
        },
      ],
      data: {},
    },
  ],
  entityMap: {
    '0': {
      type: 'wix-draft-plugin-image',
      mutability: 'IMMUTABLE',
      data: {
        config: {
          alignment: 'center',
          size: 'inline',
          showTitle: true,
          showDescription: true,
          link: {
            url: 'images.com',
            target: '_blank',
            rel: 'nofollow',
          },
        },
        src: {
          id: '980dd6e0a5fc59853b6caf447f9c73ce',
          original_file_name: '8bb438_c1089eafb4ab405ba328b528e3ecc63e.jpg',
          file_name: '8bb438_c1089eafb4ab405ba328b528e3ecc63e.jpg',
          width: 1920,
          height: 1920,
        },
        metadata: {
          caption: 'image caption',
          alt: 'alt text',
        },
      },
    },
    '1': {
      type: 'wix-draft-plugin-gallery',
      mutability: 'IMMUTABLE',
      data: {
        items: [
          {
            metadata: {
              height: 2800,
              width: 4200,
            },
            url: '8bb438_e78b371c75ce42de8719dccfc97298a4.jpg',
            itemId: '8bb438_e78b371c75ce42de8719dccfc97298a4.jpg',
          },
          {
            metadata: {
              height: 1280,
              width: 1920,
            },
            url: '8bb438_281af3d3281f4584a5a864c6c60f3a00.jpg',
            itemId: '8bb438_281af3d3281f4584a5a864c6c60f3a00.jpg',
          },
          {
            metadata: {
              height: 1081,
              width: 1621,
            },
            url: '8bb438_0795e40ac4db438a8a723ea98dbeda10.jpg',
            itemId: '8bb438_0795e40ac4db438a8a723ea98dbeda10.jpg',
          },
        ],
        styles: {
          galleryLayout: 2,
          gallerySizeType: 'px',
          gallerySizePx: 300,
          galleryMargin: 0,
          oneRow: false,
          cubeRatio: 1,
          galleryThumbnailsAlignment: 'bottom',
          isVertical: true,
          numberOfImagesPerRow: 3,
          imageMargin: 20,
          thumbnailSpacings: 0,
          cubeType: 'fill',
          enableInfiniteScroll: true,
          titlePlacement: 'SHOW_ON_HOVER',
          allowHover: false,
          itemClick: 'link',
          fullscreen: false,
          showArrows: false,
          gridStyle: 1,
          loveButton: false,
          allowSocial: false,
          allowDownload: false,
          mobileSwipeAnimation: 'NO_EFFECT',
          thumbnailSize: 120,
          gotStyleParams: true,
          cubeImages: true,
          groupSize: 1,
          groupTypes: '1',
          hasThumbnails: false,
          enableScroll: true,
          isGrid: true,
          isSlider: false,
          isColumns: false,
          isSlideshow: false,
          cropOnlyFill: false,
          smartCrop: false,
          imageResize: false,
          galleryImageRatio: 2,
          galleryType: 'Columns',
          minItemSize: 50,
          videoPlay: 'auto',
        },
        config: {
          alignment: 'center',
          size: 'content',
          layout: 'small',
          spacing: 0,
        },
      },
    },
    '2': {
      type: 'LINK',
      mutability: 'MUTABLE',
      data: {
        url: 'reddit.com',
        target: '_blank',
        rel: 'nofollow',
      },
    },
    '3': {
      type: 'wix-draft-plugin-video',
      mutability: 'IMMUTABLE',
      data: {
        config: {
          size: 'content',
          alignment: 'center',
        },
        src: 'http://mirrors.standaloneinstaller.com/video-sample/jellyfish-25-mbps-hd-hevc.mp4',
        isCustomVideo: true,
        metadata: {
          height: 270,
          author_name: 'Wix.com',
          html:
            '<iframe width="480" height="270" src="https://www.youtube.com/embed/BBu5codsO6Y?feature=oembed" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>',
          thumbnail_width: 480,
          type: 'video',
          version: '1.0',
          thumbnail_height: 360,
          provider_url: 'https://www.youtube.com/',
          title: 'iJustine | Create a Website with Wix Artificial Design Intelligence',
          thumbnail_url: 'https://i.ytimg.com/vi/BBu5codsO6Y/hqdefault.jpg',
          author_url: 'https://www.youtube.com/user/Wix',
          provider_name: 'YouTube',
          width: 480,
          video_url: 'https://youtu.be/BBu5codsO6Y',
        },
      },
    },
    '4': {
      type: 'wix-draft-plugin-divider',
      mutability: 'IMMUTABLE',
      data: {
        type: 'single',
        config: {
          size: 'large',
          alignment: 'center',
          textWrap: 'nowrap',
        },
      },
    },
    '5': {
      type: 'wix-draft-plugin-map',
      mutability: 'IMMUTABLE',
      data: {
        config: {
          size: 'content',
          alignment: 'center',
          width: 400,
          height: 400,
        },
        mapSettings: {
          address: 'Wix HQ, Nemal Tel Aviv Street, Tel Aviv-Yafo, Israel',
          locationDisplayName: 'Wix HQ, Nemal Tel Aviv Street, Tel Aviv-Yafo, Israel',
          lat: 32.097235,
          lng: 34.77427,
          zoom: 18,
          mode: 'roadmap',
          isMarkerShown: true,
          isZoomControlShown: true,
          isStreetViewControlShown: true,
          isDraggingAllowed: true,
        },
      },
    },
    '6': {
      type: 'wix-draft-plugin-file-upload',
      mutability: 'IMMUTABLE',
      data: {
        config: {
          alignment: 'left',
          size: 'small',
        },
        name: '[95438] 811 х 1187..jpg',
        type: 'jpg',
        url: '',
      },
    },
    '7': {
      type: 'mention',
      mutability: 'SEGMENTED',
      data: {
        mention: {
          name: 'Test One',
          slug: 'testone',
        },
      },
    },
    '8': {
      type: 'LINK',
      mutability: 'MUTABLE',
      data: {
        url: 'link.com',
        target: '_self',
        rel: 'noopener',
      },
    },
    '9': {
      type: 'LINK',
      mutability: 'MUTABLE',
      data: {
        url: 'more.com',
        target: '_blank',
        rel: 'noopener',
      },
    },
    '10': {
      type: 'LINK',
      mutability: 'MUTABLE',
      data: {
        url: 'links.com',
        target: '_blank',
        rel: 'noopener',
      },
    },
    '11': {
      type: 'wix-draft-plugin-giphy',
      mutability: 'IMMUTABLE',
      data: {
        config: {
          size: 'content',
          alignment: 'center',
        },
        gif: {
          originalUrl: 'https://media3.giphy.com/media/uL0lBBzFn98eQ/giphy.gif',
          stillUrl: 'https://media3.giphy.com/media/uL0lBBzFn98eQ/giphy_s.gif',
          height: 270,
          width: 360,
        },
      },
    },
  },
  VERSION: '6.6.5',
});
