export default [
  {
    id: '0227ed00-697c-42c0-bc12-f84f0ae01a84',
    name: 'Roy Birthday Party!!',
    imageSrc: 'https://static.wixstatic.com/media/7f8360_274a37551ab54326adb4c50b1e7daaa0~mv2.jpeg',
    description: "December 28, 2020 at 7:00 PM | Modi'in-Maccabim-Re'ut",
    html:
      '<style>.rtl {\n\t\tdirection: rtl;\n\t\t}\n\n\t\t.ltr {\n\t\tdirection: ltr;\n\t\t}\n\t\t.card {\n\t\twidth: 100%;\n\t\tborder: solid 1px #808080;\n\t\tbackground-color: white;\n\t\t}\n\n\t\t.image {\n\t\tbackground-size: cover;\n\t\tbackground-repeat: no-repeat;\n\t\tbackground-position: center center;\n\t\tflex: 0 0 auto;\n\t\t}\n\n\t\t@media only screen and (min-width: 650px) {\n\t\t.card {\n\t\t\tdisplay: flex;\n\t\t\tflex-direction: row;\n\t\t}\n\n\t\t.image {\n\t\t\twidth: 185px;\n\t\t}\n\t\t}\n\n\t\t@media only screen and (max-width: 649px) and (min-width: 280px) {\n\t\t.card {\n\t\t\twidth: 280px;\n\t\t}\n\n\t\t.image {\n\t\t\tpadding-bottom: 56.25%;\n\t\t}\n\t\t}</style><div class="card ltr"><div style="background-image:url(https://static.wixstatic.com/media/7f8360_274a37551ab54326adb4c50b1e7daaa0~mv2.jpeg)" class="image"></div><style>.content {\n\t\tmargin: 32px;\n\t\t}\n\n\t\t.title {\n\t\tmax-width: 306px;\n\t\tfont-family: LibreBaskerville;\n\t\tfont-size: 20px;\n\t\tline-height: 1.4;\n\t\tcolor: #000000;\n\t\t}\n\n\t\t.subtitle {\n\t\tpadding-top: 12px;\n\t\tfont-family: HelveticaNeue;\n\t\tfont-size: 14px;\n\t\tline-height: 1.43;\n\t\tcolor: #000000;\n\t\t}\n\n\t\t.right {\n\t\tpadding: 0 9.6px 0 9.6px;\n\t\t}\n\n\t\t.button {\n\t\twidth: 145px;\n\t\tdisplay: flex;\n\t\tjustify-content: center;\n\t\tbackground-color: #000000;\n\t\t}\n\n\t\t.button:hover {\n\t\t\topacity: 0.7;\n\t\t}\n\n\t\t.button:focus {\n\t\t\topacity: 0.7;\n\t\t}\n\n\t\t.link {\n\t\tpadding: 8px 16px 8px 16px;\n\t\tfont-family: HelveticaNeue;\n\t\tline-height: 1.5;\n\t\ttext-align: center;\n\t\tcolor: #ffffff;\n\t\ttext-decoration: none;\n\t\t}\n\n\t\t@media only screen and (min-width: 650px) {\n\n\t\t.content {\n\t\t\twidth: 100%;\n\t\t\tdisplay: flex;\n\t\t\tjustify-content: space-between;\n\t\t}\n\n\t\t.button {\n\t\t\theight: 40px;\n\t\t}\n\t\t}\n\n\t\t@media only screen and (max-width: 649px) and (min-width: 280px) {\n\n\t\t.content {\n\t\t\tmargin: 20px;\n\t\t\tflex-direction: column;\n\t\t}\n\n\t\t.title {\n\t\t\tmax-width: 240px;\n\t\t}\n\n\t\t.button {\n\t\t\twidth: 240px;\n\t\t\tmargin-top: 24px;\n\t\t}\n\t\t}</style><div class="content"><div><div class="title">Roy Birthday Party!!</div><div class="subtitle">December 28, 2020 at 7:00 PM<span><span class="right">|</span>Modi&#x27;in-Maccabim-Re&#x27;ut</span></div></div><div class="button"><a class="link" href="https://www.wix.app/events/54e7b326-49ec-434f-a7cc-c2ad1eaec049/0227ed00-697c-42c0-bc12-f84f0ae01a84/details?d=https://sapirs0.wixsite.com/mysite/event-details/roy-birthday-party-1" target="_blank">Register Now</a></div></div></div>',
  },
  {
    id: '65129504-3bfc-44c8-90cc-f9eedfea9321',
    name:
      '2-week course of intensive physical research, with a sense of plenty of time for process and discovery. Rooted in Ohad N',
    imageSrc: 'https://static.wixstatic.com/media/2571849c6b0749a4bbd008a06fd65762.jpg',
    description: '13 de octubre de 2020 19:00–27 de octubre de 2020 23:00 | Suzanna Baby Shop',
    html:
      '<style>.rtl {\n\t\tdirection: rtl;\n\t\t}\n\n\t\t.ltr {\n\t\tdirection: ltr;\n\t\t}\n\t\t.card {\n\t\twidth: 100%;\n\t\tborder: solid 1px #808080;\n\t\tbackground-color: white;\n\t\t}\n\n\t\t.image {\n\t\tbackground-size: cover;\n\t\tbackground-repeat: no-repeat;\n\t\tbackground-position: center center;\n\t\tflex: 0 0 auto;\n\t\t}\n\n\t\t@media only screen and (min-width: 650px) {\n\t\t.card {\n\t\t\tdisplay: flex;\n\t\t\tflex-direction: row;\n\t\t}\n\n\t\t.image {\n\t\t\twidth: 185px;\n\t\t}\n\t\t}\n\n\t\t@media only screen and (max-width: 649px) and (min-width: 280px) {\n\t\t.card {\n\t\t\twidth: 280px;\n\t\t}\n\n\t\t.image {\n\t\t\tpadding-bottom: 56.25%;\n\t\t}\n\t\t}</style><div class="card ltr"><div style="background-image:url(https://static.wixstatic.com/media/2571849c6b0749a4bbd008a06fd65762.jpg)" class="image"></div><style>.content {\n\t\tmargin: 32px;\n\t\t}\n\n\t\t.title {\n\t\tmax-width: 306px;\n\t\tfont-family: LibreBaskerville;\n\t\tfont-size: 20px;\n\t\tline-height: 1.4;\n\t\tcolor: #000000;\n\t\t}\n\n\t\t.subtitle {\n\t\tpadding-top: 12px;\n\t\tfont-family: Avenir;\n\t\tfont-size: 14px;\n\t\tline-height: 1.43;\n\t\tcolor: #000000;\n\t\t}\n\n\t\t.right {\n\t\tpadding: 0 9.6px 0 9.6px;\n\t\t}\n\n\t\t.button {\n\t\twidth: 145px;\n\t\tdisplay: flex;\n\t\tjustify-content: center;\n\t\tbackground-color: #000000;\n\t\t}\n\n\t\t.button:hover {\n\t\t\topacity: 0.7;\n\t\t}\n\n\t\t.button:focus {\n\t\t\topacity: 0.7;\n\t\t}\n\n\t\t.link {\n\t\tpadding: 8px 16px 8px 16px;\n\t\tfont-family: Avenir;\n\t\tline-height: 1.5;\n\t\ttext-align: center;\n\t\tcolor: #ffffff;\n\t\ttext-decoration: none;\n\t\t}\n\n\t\t@media only screen and (min-width: 650px) {\n\n\t\t.content {\n\t\t\twidth: 100%;\n\t\t\tdisplay: flex;\n\t\t\tjustify-content: space-between;\n\t\t}\n\n\t\t.button {\n\t\t\theight: 40px;\n\t\t}\n\t\t}\n\n\t\t@media only screen and (max-width: 649px) and (min-width: 280px) {\n\n\t\t.content {\n\t\t\tmargin: 20px;\n\t\t\tflex-direction: column;\n\t\t}\n\n\t\t.title {\n\t\t\tmax-width: 240px;\n\t\t}\n\n\t\t.button {\n\t\t\twidth: 240px;\n\t\t\tmargin-top: 24px;\n\t\t}\n\t\t}</style><div class="content"><div><div class="title">2-week course of intensive physical research, with a sense of plenty of time for process and discovery. Rooted in Ohad N</div><div class="subtitle">13 de octubre de 2020 19:00–27 de octubre de 2020 23:00<span><span class="right">|</span>Suzanna Baby Shop</span></div></div><div class="button"><a class="link" href="https://www.wix.app/events/54e7b326-49ec-434f-a7cc-c2ad1eaec049/65129504-3bfc-44c8-90cc-f9eedfea9321/details?d=https://sapirs0.wixsite.com/mysite/event-details/2-week-course-of-intensive-physical-research-with-a-sense-of-plenty-of-time-for-process-and-discovery-rooted-in-ohad-n" target="_blank">Regístrate</a></div></div></div>',
  },
];
