export default [
  {
    id: '03ef6546-985d-4739-951e-ca897375b967',
    name: 'CUPCAKE MASTER',
    imageSrc: 'https://static.wixstatic.com/media/78ccafc88f7fce3e55bd7a33f166704b.jpg',
    description: '115 ILS',
    html:
      '<style>.rtl {\n\t\tdirection: rtl;\n\t\t}\n\n\t\t.ltr {\n\t\tdirection: ltr;\n\t\t}\n\t\t.card {\n\t\twidth: 100%;\n\t\tborder: solid 1px #808080;\n\t\tbackground-color: white;\n\t\t}\n\n\t\t.image {\n\t\tbackground-size: cover;\n\t\tbackground-repeat: no-repeat;\n\t\tbackground-position: center center;\n\t\tflex: 0 0 auto;\n\t\t}\n\n\t\t@media only screen and (min-width: 650px) {\n\t\t.card {\n\t\t\tdisplay: flex;\n\t\t\tflex-direction: row;\n\t\t}\n\n\t\t.image {\n\t\t\twidth: 185px;\n\t\t}\n\t\t}\n\n\t\t@media only screen and (max-width: 649px) and (min-width: 280px) {\n\t\t.card {\n\t\t\twidth: 280px;\n\t\t}\n\n\t\t.image {\n\t\t\tpadding-bottom: 56.25%;\n\t\t}\n\t\t}</style><div class="card ltr"><div style="background-image:url(https://static.wixstatic.com/media/78ccafc88f7fce3e55bd7a33f166704b.jpg)" class="image"></div><style>.content {\n\t\tmargin: 32px;\n\t\t}\n\n\t\t.title {\n\t\tmax-width: 306px;\n\t\tfont-family: LibreBaskerville;\n\t\tfont-size: 20px;\n\t\tline-height: 1.4;\n\t\tcolor: #000000;\n\t\t}\n\n\t\t.subtitle {\n\t\tpadding-top: 12px;\n\t\tfont-family: HelveticaNeue;\n\t\tfont-size: 14px;\n\t\tline-height: 1.43;\n\t\tcolor: #000000;\n\t\t}\n\n\t\t.right {\n\t\tpadding: 0 9.6px 0 9.6px;\n\t\t}\n\n\t\t.button {\n\t\twidth: 145px;\n\t\tdisplay: flex;\n\t\tjustify-content: center;\n\t\tbackground-color: #000000;\n\t\t}\n\n\t\t.button:hover {\n\t\t\topacity: 0.7;\n\t\t}\n\n\t\t.button:focus {\n\t\t\topacity: 0.7;\n\t\t}\n\n\t\t.link {\n\t\tpadding: 8px 16px 8px 16px;\n\t\tfont-family: HelveticaNeue;\n\t\tline-height: 1.5;\n\t\ttext-align: center;\n\t\tcolor: #ffffff;\n\t\ttext-decoration: none;\n\t\t}\n\n\t\t@media only screen and (min-width: 650px) {\n\n\t\t.content {\n\t\t\twidth: 100%;\n\t\t\tdisplay: flex;\n\t\t\tjustify-content: space-between;\n\t\t}\n\n\t\t.button {\n\t\t\theight: 40px;\n\t\t}\n\t\t}\n\n\t\t@media only screen and (max-width: 649px) and (min-width: 280px) {\n\n\t\t.content {\n\t\t\tmargin: 20px;\n\t\t\tflex-direction: column;\n\t\t}\n\n\t\t.title {\n\t\t\tmax-width: 240px;\n\t\t}\n\n\t\t.button {\n\t\t\twidth: 240px;\n\t\t\tmargin-top: 24px;\n\t\t}\n\t\t}</style><div class="content"><div><div class="title">CUPCAKE MASTER</div><div class="subtitle">90</div></div><div class="button"><a class="link" href="https://www.wix.app/bookings/54e7b326-49ec-434f-a7cc-c2ad1eaec049/service/03ef6546-985d-4739-951e-ca897375b967/details?d=https://sapirs0.wixsite.com/mysite/bookings-checkout/cupcake-master" target="_blank">Book Now</a></div></div></div>',
  },
  {
    id: '05ea21a5-6bae-41d6-bb83-a67ce7b7eaae',
    name: 'BAKING',
    imageSrc: 'https://static.wixstatic.com/media/6fb7a82098b749b8bd98773dc3bf6aea.jpg',
    description: '65 ILS',
    html:
      '<style>.rtl {\n\t\tdirection: rtl;\n\t\t}\n\n\t\t.ltr {\n\t\tdirection: ltr;\n\t\t}\n\t\t.card {\n\t\twidth: 100%;\n\t\tborder: solid 1px #808080;\n\t\tbackground-color: white;\n\t\t}\n\n\t\t.image {\n\t\tbackground-size: cover;\n\t\tbackground-repeat: no-repeat;\n\t\tbackground-position: center center;\n\t\tflex: 0 0 auto;\n\t\t}\n\n\t\t@media only screen and (min-width: 650px) {\n\t\t.card {\n\t\t\tdisplay: flex;\n\t\t\tflex-direction: row;\n\t\t}\n\n\t\t.image {\n\t\t\twidth: 185px;\n\t\t}\n\t\t}\n\n\t\t@media only screen and (max-width: 649px) and (min-width: 280px) {\n\t\t.card {\n\t\t\twidth: 280px;\n\t\t}\n\n\t\t.image {\n\t\t\tpadding-bottom: 56.25%;\n\t\t}\n\t\t}</style><div class="card ltr"><div style="background-image:url(https://static.wixstatic.com/media/6fb7a82098b749b8bd98773dc3bf6aea.jpg)" class="image"></div><style>.content {\n\t\tmargin: 32px;\n\t\t}\n\n\t\t.title {\n\t\tmax-width: 306px;\n\t\tfont-family: LibreBaskerville;\n\t\tfont-size: 20px;\n\t\tline-height: 1.4;\n\t\tcolor: #000000;\n\t\t}\n\n\t\t.subtitle {\n\t\tpadding-top: 12px;\n\t\tfont-family: HelveticaNeue;\n\t\tfont-size: 14px;\n\t\tline-height: 1.43;\n\t\tcolor: #000000;\n\t\t}\n\n\t\t.right {\n\t\tpadding: 0 9.6px 0 9.6px;\n\t\t}\n\n\t\t.button {\n\t\twidth: 145px;\n\t\tdisplay: flex;\n\t\tjustify-content: center;\n\t\tbackground-color: #000000;\n\t\t}\n\n\t\t.button:hover {\n\t\t\topacity: 0.7;\n\t\t}\n\n\t\t.button:focus {\n\t\t\topacity: 0.7;\n\t\t}\n\n\t\t.link {\n\t\tpadding: 8px 16px 8px 16px;\n\t\tfont-family: HelveticaNeue;\n\t\tline-height: 1.5;\n\t\ttext-align: center;\n\t\tcolor: #ffffff;\n\t\ttext-decoration: none;\n\t\t}\n\n\t\t@media only screen and (min-width: 650px) {\n\n\t\t.content {\n\t\t\twidth: 100%;\n\t\t\tdisplay: flex;\n\t\t\tjustify-content: space-between;\n\t\t}\n\n\t\t.button {\n\t\t\theight: 40px;\n\t\t}\n\t\t}\n\n\t\t@media only screen and (max-width: 649px) and (min-width: 280px) {\n\n\t\t.content {\n\t\t\tmargin: 20px;\n\t\t\tflex-direction: column;\n\t\t}\n\n\t\t.title {\n\t\t\tmax-width: 240px;\n\t\t}\n\n\t\t.button {\n\t\t\twidth: 240px;\n\t\t\tmargin-top: 24px;\n\t\t}\n\t\t}</style><div class="content"><div><div class="title">BAKING</div></div><div class="button"><a class="link" href="https://www.wix.app/bookings/54e7b326-49ec-434f-a7cc-c2ad1eaec049/service/05ea21a5-6bae-41d6-bb83-a67ce7b7eaae/details?d=https://sapirs0.wixsite.com/mysite/bookings-checkout/baking" target="_blank">Book Now</a></div></div></div>',
  },
  {
    id: 'cce8a1e7-29df-40de-84bc-fda86bb6af03',
    name: 'New Service',
    description: '100 ILS',
    html:
      '<style>.rtl {\n\t\tdirection: rtl;\n\t\t}\n\n\t\t.ltr {\n\t\tdirection: ltr;\n\t\t}\n\t\t.card {\n\t\twidth: 100%;\n\t\tborder: solid 1px #808080;\n\t\tbackground-color: white;\n\t\t}\n\n\t\t.image {\n\t\tbackground-size: cover;\n\t\tbackground-repeat: no-repeat;\n\t\tbackground-position: center center;\n\t\tflex: 0 0 auto;\n\t\t}\n\n\t\t@media only screen and (min-width: 650px) {\n\t\t.card {\n\t\t\tdisplay: flex;\n\t\t\tflex-direction: row;\n\t\t}\n\n\t\t.image {\n\t\t\twidth: 185px;\n\t\t}\n\t\t}\n\n\t\t@media only screen and (max-width: 649px) and (min-width: 280px) {\n\t\t.card {\n\t\t\twidth: 280px;\n\t\t}\n\n\t\t.image {\n\t\t\tpadding-bottom: 56.25%;\n\t\t}\n\t\t}</style><div class="card ltr"><style>.content {\n\t\tmargin: 32px;\n\t\t}\n\n\t\t.title {\n\t\tmax-width: 306px;\n\t\tfont-family: LibreBaskerville;\n\t\tfont-size: 20px;\n\t\tline-height: 1.4;\n\t\tcolor: #000000;\n\t\t}\n\n\t\t.subtitle {\n\t\tpadding-top: 12px;\n\t\tfont-family: HelveticaNeue;\n\t\tfont-size: 14px;\n\t\tline-height: 1.43;\n\t\tcolor: #000000;\n\t\t}\n\n\t\t.right {\n\t\tpadding: 0 9.6px 0 9.6px;\n\t\t}\n\n\t\t.button {\n\t\twidth: 145px;\n\t\tdisplay: flex;\n\t\tjustify-content: center;\n\t\tbackground-color: #000000;\n\t\t}\n\n\t\t.button:hover {\n\t\t\topacity: 0.7;\n\t\t}\n\n\t\t.button:focus {\n\t\t\topacity: 0.7;\n\t\t}\n\n\t\t.link {\n\t\tpadding: 8px 16px 8px 16px;\n\t\tfont-family: HelveticaNeue;\n\t\tline-height: 1.5;\n\t\ttext-align: center;\n\t\tcolor: #ffffff;\n\t\ttext-decoration: none;\n\t\t}\n\n\t\t@media only screen and (min-width: 650px) {\n\n\t\t.content {\n\t\t\twidth: 100%;\n\t\t\tdisplay: flex;\n\t\t\tjustify-content: space-between;\n\t\t}\n\n\t\t.button {\n\t\t\theight: 40px;\n\t\t}\n\t\t}\n\n\t\t@media only screen and (max-width: 649px) and (min-width: 280px) {\n\n\t\t.content {\n\t\t\tmargin: 20px;\n\t\t\tflex-direction: column;\n\t\t}\n\n\t\t.title {\n\t\t\tmax-width: 240px;\n\t\t}\n\n\t\t.button {\n\t\t\twidth: 240px;\n\t\t\tmargin-top: 24px;\n\t\t}\n\t\t}</style><div class="content"><div><div class="title">New Service</div><div class="subtitle">45</div></div><div class="button"><a class="link" href="https://www.wix.app/bookings/54e7b326-49ec-434f-a7cc-c2ad1eaec049/service/cce8a1e7-29df-40de-84bc-fda86bb6af03/details?d=https://sapirs0.wixsite.com/mysite/bookings-checkout/new-service" target="_blank">Book Now</a></div></div></div>',
  },
  {
    id: 'ce5e4de0-5428-4a39-be82-3126fe53f42e',
    name: 'FROSTING',
    imageSrc: 'https://static.wixstatic.com/media/87141f9c9a074b11b38181fb303ba00a.jpg',
    description: '87 ILS',
    html:
      '<style>.rtl {\n\t\tdirection: rtl;\n\t\t}\n\n\t\t.ltr {\n\t\tdirection: ltr;\n\t\t}\n\t\t.card {\n\t\twidth: 100%;\n\t\tborder: solid 1px #808080;\n\t\tbackground-color: white;\n\t\t}\n\n\t\t.image {\n\t\tbackground-size: cover;\n\t\tbackground-repeat: no-repeat;\n\t\tbackground-position: center center;\n\t\tflex: 0 0 auto;\n\t\t}\n\n\t\t@media only screen and (min-width: 650px) {\n\t\t.card {\n\t\t\tdisplay: flex;\n\t\t\tflex-direction: row;\n\t\t}\n\n\t\t.image {\n\t\t\twidth: 185px;\n\t\t}\n\t\t}\n\n\t\t@media only screen and (max-width: 649px) and (min-width: 280px) {\n\t\t.card {\n\t\t\twidth: 280px;\n\t\t}\n\n\t\t.image {\n\t\t\tpadding-bottom: 56.25%;\n\t\t}\n\t\t}</style><div class="card ltr"><div style="background-image:url(https://static.wixstatic.com/media/87141f9c9a074b11b38181fb303ba00a.jpg)" class="image"></div><style>.content {\n\t\tmargin: 32px;\n\t\t}\n\n\t\t.title {\n\t\tmax-width: 306px;\n\t\tfont-family: LibreBaskerville;\n\t\tfont-size: 20px;\n\t\tline-height: 1.4;\n\t\tcolor: #000000;\n\t\t}\n\n\t\t.subtitle {\n\t\tpadding-top: 12px;\n\t\tfont-family: HelveticaNeue;\n\t\tfont-size: 14px;\n\t\tline-height: 1.43;\n\t\tcolor: #000000;\n\t\t}\n\n\t\t.right {\n\t\tpadding: 0 9.6px 0 9.6px;\n\t\t}\n\n\t\t.button {\n\t\twidth: 145px;\n\t\tdisplay: flex;\n\t\tjustify-content: center;\n\t\tbackground-color: #000000;\n\t\t}\n\n\t\t.button:hover {\n\t\t\topacity: 0.7;\n\t\t}\n\n\t\t.button:focus {\n\t\t\topacity: 0.7;\n\t\t}\n\n\t\t.link {\n\t\tpadding: 8px 16px 8px 16px;\n\t\tfont-family: HelveticaNeue;\n\t\tline-height: 1.5;\n\t\ttext-align: center;\n\t\tcolor: #ffffff;\n\t\ttext-decoration: none;\n\t\t}\n\n\t\t@media only screen and (min-width: 650px) {\n\n\t\t.content {\n\t\t\twidth: 100%;\n\t\t\tdisplay: flex;\n\t\t\tjustify-content: space-between;\n\t\t}\n\n\t\t.button {\n\t\t\theight: 40px;\n\t\t}\n\t\t}\n\n\t\t@media only screen and (max-width: 649px) and (min-width: 280px) {\n\n\t\t.content {\n\t\t\tmargin: 20px;\n\t\t\tflex-direction: column;\n\t\t}\n\n\t\t.title {\n\t\t\tmax-width: 240px;\n\t\t}\n\n\t\t.button {\n\t\t\twidth: 240px;\n\t\t\tmargin-top: 24px;\n\t\t}\n\t\t}</style><div class="content"><div><div class="title">FROSTING</div></div><div class="button"><a class="link" href="https://www.wix.app/bookings/54e7b326-49ec-434f-a7cc-c2ad1eaec049/service/ce5e4de0-5428-4a39-be82-3126fe53f42e/details?d=https://sapirs0.wixsite.com/mysite/bookings-checkout/frosting" target="_blank">Book Now</a></div></div></div>',
  },
];
